stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY site@msaserj.ru "
      rm -fr ~/site &&
      git clone https://gitlab.com/msaserj/inc-portfolio.git ~/site &&
      rm -fr /var/www/html/msaserj/ &&
      cp -r ~/site/build/ /var/www/html/msaserj/ &&
      rm -fr ~/site "
